# Generated by Django 6.0 on 2026-01-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecu',
            name='ecu_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ecu',
            name='password',
            field=models.CharField(max_length=64),
        ),
    ]
