# Generated by Django 6.0 on 2026-01-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_ecu_ecu_id_alter_ecu_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecu',
            name='password',
        ),
        migrations.RemoveField(
            model_name='ecu',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='ecu',
            name='password_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
