# Generated by Django 6.0 on 2026-01-05 17:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_ecu_password_remove_ecu_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecu',
            name='is_locked',
        ),
        migrations.AddField(
            model_name='ecu',
            name='status',
            field=models.CharField(choices=[('LOCKED', 'Locked'), ('UNLOCKED', 'Unlocked')], default='LOCKED', max_length=10),
        ),
        migrations.AlterField(
            model_name='ecu',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ecu',
            name='ecu_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ecu',
            name='password_hash',
            field=models.CharField(max_length=128),
        ),
    ]
