# Generated by Django 6.0 on 2026-01-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_ecu_is_locked_ecu_status_alter_ecu_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ecu',
            name='ecu_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ecu',
            name='status',
            field=models.CharField(default='LOCKED', max_length=10),
        ),
    ]
