# Generated by Django 6.0 on 2026-01-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_ecu_created_at_alter_ecu_ecu_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecu',
            name='password_hash',
            field=models.CharField(max_length=64),
        ),
    ]
